"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-03 23:23:16.063744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('debit', 'credit', 'cash', 'savings', name='accounttype'), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fx_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('usd_cop', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fx_rate_date'), 'fx_rate', ['date'], unique=True)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('is_income', sa.Boolean(), nullable=False),
    sa.Column('exclude_from_budget', sa.Boolean(), nullable=False),
    sa.Column('exclude_from_totals', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['category_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_amount', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('monthly_amount', sa.Integer(), nullable=False),
    sa.Column('savings_account_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'reached', 'paused', name='goalstatus'), nullable=False),
    sa.ForeignKeyConstraint(['savings_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_source_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['default_source_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Seed the singleton Settings row that the previous init_db() inserted.
    # Done after create_table('settings') above; folded into 0001 so we don't need a 0002 for one INSERT.
    op.execute("INSERT INTO settings (id, base_currency) VALUES (1, 'COP')")
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('year_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_assigned', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'year_month', name='uq_budget_category_month')
    )
    op.create_table('recurring_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payee', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('expense', 'income', 'transfer', name='txtype'), nullable=False),
    sa.Column('mode', sa.Enum('auto', 'manual', name='recurringmode'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('interval_unit', sa.Enum('day', 'week', 'month', 'year', name='intervalunit'), nullable=False),
    sa.Column('interval_count', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('payee', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sa.Enum('expense', 'income', 'transfer', name='txtype'), nullable=False),
    sa.Column('status', sa.Enum('planned', 'posted', 'skipped', name='txstatus'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('to_base', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('recurring_id', sa.Integer(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('transfer_group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'agent', 'import_', name='source'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.ForeignKeyConstraint(['recurring_id'], ['recurring_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_transfer_group_id'), 'transaction', ['transfer_group_id'], unique=False)
    op.create_table('goal_contribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('confirmed', 'manual', name='contributionsource'), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_goal_contribution_goal_date', 'goal_contribution', ['goal_id', 'date'], unique=False)
    op.create_table('recurring_occurrence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurring_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('posted', 'planned', 'skipped', name='occurrencestatus'), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recurring_id'], ['recurring_item.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recurring_id', 'due_date', name='uq_occurrence_recurring_due')
    )
    op.create_index(op.f('ix_recurring_occurrence_recurring_id'), 'recurring_occurrence', ['recurring_id'], unique=False)
    op.create_table('transaction_tag',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('transaction_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_tag')
    op.drop_index(op.f('ix_recurring_occurrence_recurring_id'), table_name='recurring_occurrence')
    op.drop_table('recurring_occurrence')
    op.drop_index('ix_goal_contribution_goal_date', table_name='goal_contribution')
    op.drop_table('goal_contribution')
    op.drop_index(op.f('ix_transaction_transfer_group_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_table('recurring_item')
    op.drop_table('budget')
    op.drop_table('settings')
    op.drop_table('goal')
    op.drop_table('category')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_fx_rate_date'), table_name='fx_rate')
    op.drop_table('fx_rate')
    op.drop_table('category_group')
    op.drop_table('account')
    # ### end Alembic commands ###
