# Quaestor — dev recipes.
#
# Quick start:
#   just dev-build   # one-time image build (~1-2 min)
#   just dev         # bring up the stack (foreground, Ctrl-C stops)
#   just dev-logs    # follow logs from all services
#
# When you're done:
#   just dev-down    # stop, keep .dev-data/
#   just dev-reset   # wipe .dev-data/ and restart api+mcp

_default:
	@just --list

# Start the dev stack (foreground; Ctrl-C stops).
dev:
	docker compose up

# Build images first (cold start or after pulling new source).
dev-build:
	docker compose build

# Follow logs from all services.
dev-logs:
	docker compose logs -f

# Follow logs from a single service, e.g. `just dev-logs-one api`.
dev-logs-one service:
	docker compose logs -f {{service}}

# Stop the stack. Keeps ./.dev-data/quaestor.db intact.
dev-down:
	docker compose down

# Drop the db + backups volumes and restart fresh.
dev-reset:
	docker compose down -v
	docker compose up api mcp scheduler db

# Manually run the daily job once (FX + materialize_due + ensure_month_closed).
# Requires P7's quaestor.jobs.daily module to be shipped.
dev-trigger-scheduler:
	docker compose exec scheduler uv run python -m quaestor.jobs.daily

# Open a shell in the api container.
dev-shell-api:
	docker compose exec api sh

# Run the backend test suite on the host (in-memory DB; does not touch db volume).
dev-test:
	cd backend && uv run pytest -q

# Run alembic upgrade head against the live stack.
db-upgrade:
	docker compose exec api uv run alembic upgrade head

# Downgrade by N revisions. Default = 1.
db-downgrade rev="-1":
	docker compose exec api uv run alembic downgrade {{rev}}

# Generate a new autogenerated revision. Default message for tests.
db-revision msg="schema change":
	docker compose exec api uv run alembic revision --autogenerate -m "{{msg}}"

# Open psql against the running db service.
db-shell:
	docker compose exec db psql -U quaestor -d quaestor

# Take a manual pg_dump into /backups.
db-backup-now:
	docker compose exec scheduler sh -c 'pg_dump -U quaestor -h db -Fc quaestor > /backups/quaestor-manual-$(date -u +%FT%H%MZ).dump && ls /backups'
