#!/usr/bin/env python3
"""Acceptance test generator — reads a feature's fixed JSON IR and emits pytest.

Usage:
    python3 acceptance/generator.py <feature-dir> [<feature-dir> ...]

For each feature dir (e.g. ``features/005-fx-read-time-conversion``):

- reads  ``<feature-dir>/.build/spec.json``   (IR from dae_gherkin.py)
- writes ``<feature-dir>/.build/generated/conftest.py``
- writes ``<feature-dir>/.build/generated/test_<feature_slug>.py``

One scenario -> one test function; one example row -> one parametrised
execution (``<param>`` placeholders resolved at generation time, so the
generated file shows fully-resolved, readable step texts). The generator
reads ONLY the IR — it never parses ``spec.md``. Output is deterministic
for a fixed IR. Do not hand-edit anything under ``.build/generated/``.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

_HEADER = (
    "# GENERATED by acceptance/generator.py — DO NOT EDIT.\n"
    "# Regenerate via ./run-acceptance-tests.sh (spec.md is the source of truth).\n"
)

_PLACEHOLDER = re.compile(r"<([^<>]+)>")


def _sanitize(name: str) -> str:
    return re.sub(r"[^0-9a-zA-Z]+", "_", name).strip("_").lower()


def _resolve_steps(
    scenario: dict, row: dict[str, str] | None
) -> list[tuple[str, str]]:
    """Resolve <param> placeholders for one execution; fail-fast markers on gaps."""
    steps: list[tuple[str, str]] = []
    for s in scenario["steps"]:
        text = s["text"]
        if row is not None:
            for key, value in row.items():
                text = text.replace(f"<{key}>", value)
        missing = _PLACEHOLDER.findall(text)
        if missing:
            return [(
                "__FAIL__",
                f"missing example value(s) {missing} for step {s['text']!r}",
            )]
        steps.append((s["keyword"], text))
    return steps


def _steps_literal(steps: list[tuple[str, str]], indent: str) -> str:
    lines = [f"{indent}({keyword!r}, {text!r})," for keyword, text in steps]
    return "\n".join(lines)


def _emit_test_module(feature_dir: Path, ir: dict) -> str:
    spec_rel = (feature_dir / "spec.md").relative_to(REPO_ROOT).as_posix()
    out = [
        _HEADER,
        f"# Source spec: {spec_rel}",
        f"# Feature: {ir['name']}",
        "",
        "import pytest",
        "",
        "from acceptance.handlers import run_scenario",
        "",
        f"SPEC = {spec_rel!r}",
        "",
    ]

    seen: dict[str, int] = {}
    for scenario in ir["scenarios"]:
        base = f"test_{_sanitize(scenario['name'])}"
        seen[base] = seen.get(base, 0) + 1
        fn_name = base if seen[base] == 1 else f"{base}_{seen[base]}"
        examples = scenario.get("examples") or []

        out.append("")
        if not examples:
            steps = _resolve_steps(scenario, None)
            out += [
                f"def {fn_name}(world):",
                f"    \"\"\"Scenario: {scenario['name']}\"\"\"",
                f"    run_scenario(world, SPEC, {scenario['name']!r}, [",
                _steps_literal(steps, "        "),
                "    ])",
                "",
            ]
        else:
            out.append("@pytest.mark.parametrize(\"steps\", [")
            for i, row in enumerate(examples, start=1):
                steps = _resolve_steps(scenario, row)
                out += [
                    "    pytest.param([",
                    _steps_literal(steps, "        "),
                    f"    ], id=\"example-{i}\"),",
                ]
            out += [
                "])",
                f"def {fn_name}(world, steps):",
                f"    \"\"\"Scenario Outline: {scenario['name']}\"\"\"",
                f"    run_scenario(world, SPEC, {scenario['name']!r}, steps)",
                "",
            ]
    return "\n".join(out).rstrip() + "\n"


def _emit_conftest(generated_dir: Path) -> str:
    depth = len(generated_dir.relative_to(REPO_ROOT).parts)
    return f"""{_HEADER}
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[{depth}]
for _p in (_REPO_ROOT, _REPO_ROOT / "backend" / "src"):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

import pytest

from acceptance.handlers import new_world


@pytest.fixture
def world():
    \"\"\"Fresh application state (in-memory DB) for every scenario execution.\"\"\"
    w = new_world()
    try:
        yield w
    finally:
        w.close()
"""


def generate(feature_dir: Path) -> Path:
    feature_dir = feature_dir.resolve()
    ir_path = feature_dir / ".build" / "spec.json"
    if not ir_path.is_file():
        raise SystemExit(
            f"error: {ir_path} not found — run dae_gherkin.py first "
            "(or use ./run-acceptance-tests.sh)"
        )
    ir = json.loads(ir_path.read_text(encoding="utf-8"))

    generated_dir = feature_dir / ".build" / "generated"
    generated_dir.mkdir(parents=True, exist_ok=True)

    slug = _sanitize(feature_dir.name)
    (generated_dir / "conftest.py").write_text(
        _emit_conftest(generated_dir), encoding="utf-8"
    )
    test_path = generated_dir / f"test_{slug}.py"
    test_path.write_text(_emit_test_module(feature_dir, ir), encoding="utf-8")

    n = len(ir["scenarios"])
    print(f"generated {test_path.relative_to(REPO_ROOT)} ({n} scenarios)")
    return generated_dir


def main(argv: list[str]) -> int:
    if not argv:
        print(__doc__, file=sys.stderr)
        return 2
    for arg in argv:
        generate(Path(arg))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
